const num1 = prompt('Digite um número:')
const num2 = prompt('Digite outro número:')
const resul = Number(num1) + Number(num2)
alert(`A soma dos números digitado é: ${resul}`)
//console.log(`A soma dos números digitado é: ${resul}`)